package handler

import (
	"context"
	"crypto/md5"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/Ijon6k/Taskure/apps/api/internal/storage"
	"github.com/gin-gonic/gin"
)

type StorageHandler struct {
	storage storage.StorageService
}

func NewStorageHandler(storage storage.StorageService) *StorageHandler {
	return &StorageHandler{storage: storage}
}

// thumbBase strips every derived suffix (".webp", "_preview.webp", "_<w>.webp")
// plus any original extension, returning the extension-free object base. The
// ".webp" branch also strips the preceding original extension so legacy
// double-suffixed URLs ("file.jpg.webp") collapse to the same base the worker
// keys variants under ("file").
func thumbBase(relPath string) string {
	lower := strings.ToLower(relPath)
	switch {
	case strings.HasSuffix(lower, "_preview.webp"):
		return strings.TrimSuffix(relPath, "_preview.webp")
	case strings.HasSuffix(lower, ".webp"):
		base := strings.TrimSuffix(relPath, ".webp")
		return strings.TrimSuffix(base, filepath.Ext(base))
	default:
		return strings.TrimSuffix(relPath, filepath.Ext(relPath))
	}
}

// generatedThumbWidth returns the width embedded in a persisted thumb key
// (e.g. "file_400.webp" -> 400), or 0 if relPath is not such a key.
func generatedThumbWidth(relPath string) int {
	lower := strings.ToLower(relPath)
	if !strings.HasSuffix(lower, ".webp") || strings.HasSuffix(lower, "_preview.webp") {
		return 0
	}
	stem := strings.TrimSuffix(relPath, ".webp")
	idx := strings.LastIndexByte(stem, '_')
	if idx < 0 {
		return 0
	}
	w, err := strconv.Atoi(stem[idx+1:])
	if err != nil {
		return 0
	}
	if w <= 0 || !storage.IsThumbWidth(w) {
		return 0
	}
	return w
}

func (h *StorageHandler) objectExists(ctx context.Context, objectKey string) bool {
	if h.storage != nil {
		ok, err := h.storage.ObjectExists(ctx, objectKey)
		return err == nil && ok
	}
	// Local fallback storage (no MinIO configured).
	if strings.Contains(objectKey, "..") {
		return false
	}
	fi, err := os.Stat(filepath.Join("storage", "kanban-uploads", objectKey))
	return err == nil && !fi.IsDir()
}

// serveObject streams an object with cache headers, honoring If-None-Match.
func (h *StorageHandler) serveObject(c *gin.Context, objectKey, contentType, etag string) {
	c.Header("Cache-Control", "public, max-age=31536000, immutable")
	if etag != "" {
		c.Header("ETag", etag)
		if c.GetHeader("If-None-Match") == etag {
			c.Status(http.StatusNotModified)
			return
		}
	}

	reader, err := h.getObjectReader(c.Request.Context(), objectKey)
	if err != nil {
		c.String(http.StatusNotFound, "File not found")
		return
	}
	defer reader.Close()

	c.Header("Content-Type", contentType)
	if _, err := io.Copy(c.Writer, reader); err != nil {
		c.AbortWithStatus(http.StatusNotFound)
	}
}

// serveGeneratedOrOriginal serves a generated webp key (preview/thumb) directly
// when it exists, a preview for legacy ".webp" requests, and otherwise streams
// the original file. variantReq marks a request for a derived variant (a "?w="
// query or a generated key); its original fallback is short-cached so the
// generated variant is picked up once the background worker has produced it.
func (h *StorageHandler) serveGeneratedOrOriginal(c *gin.Context, relPath string, variantReq bool) {
	if generatedThumbWidth(relPath) != 0 || strings.HasSuffix(strings.ToLower(relPath), "_preview.webp") {
		if h.objectExists(c.Request.Context(), relPath) {
			h.serveObject(c, relPath, "image/webp", "")
			return
		}
	}
	if strings.HasSuffix(strings.ToLower(relPath), ".webp") {
		base := strings.TrimSuffix(relPath, ".webp")
		previewKey := base + "_preview.webp"
		if h.objectExists(c.Request.Context(), previewKey) {
			h.serveObject(c, previewKey, "image/webp", "")
			return
		}
	}
	h.serveOriginal(c, relPath, variantReq)
}

func (h *StorageHandler) ServeStorageFile(c *gin.Context) {
	relPath := c.Param("filepath")
	relPath = strings.TrimPrefix(relPath, "/")

	// Reject path traversal attempts up front; object keys never contain "..".
	if relPath == "" || strings.Contains(relPath, "..") {
		c.String(http.StatusNotFound, "File not found")
		return
	}

	// Strip bucket prefixes if present
	relPath = strings.TrimPrefix(relPath, "kanban-uploads/")
	relPath = strings.TrimPrefix(relPath, "kanban-assets/")

	wStr := c.Query("w")
	if wStr == "" {
		wStr = c.Query("width")
	}

	// No width requested: serve the exact original (or a generated webp key).
	if wStr == "" {
		h.serveGeneratedOrOriginal(c, relPath, false)
		return
	}

	targetW, err := strconv.Atoi(wStr)
	if err != nil || targetW <= 0 || targetW > 3840 {
		h.serveGeneratedOrOriginal(c, relPath, true)
		return
	}

	base := thumbBase(relPath)
	if base == "" {
		h.serveGeneratedOrOriginal(c, relPath, true)
		return
	}

	thumbKey := fmt.Sprintf("%s_%d.webp", base, targetW)
	etag := fmt.Sprintf("\"%x\"", md5.Sum([]byte(thumbKey)))

	// All variants are generated by the background worker, so serving a
	// thumbnail is a pure read: no decoding or resizing happens on the request
	// path.
	if h.objectExists(c.Request.Context(), thumbKey) {
		h.serveObject(c, thumbKey, "image/webp", etag)
		return
	}

	// Missing variant: the worker may still be producing it. Signal "not ready"
	// (uncached 404) instead of streaming the full-size original, so thumbnail
	// requests never drag the page down. The frontend retries until the variant
	// appears and falls back to the original for legacy files that never get
	// one.
	c.Header("Cache-Control", "no-store")
	c.String(http.StatusNotFound, "Variant not ready")
}

func (h *StorageHandler) serveOriginal(c *gin.Context, relPath string, variantReq bool) {
	ctx := c.Request.Context()
	reader, err := h.getObjectReader(ctx, relPath)
	if err != nil {
		c.String(http.StatusNotFound, "File not found")
		return
	}
	defer reader.Close()

	ext := filepath.Ext(relPath)
	switch strings.ToLower(ext) {
	case ".png":
		c.Header("Content-Type", "image/png")
	case ".jpg", ".jpeg":
		c.Header("Content-Type", "image/jpeg")
	case ".gif":
		c.Header("Content-Type", "image/gif")
	case ".webp":
		c.Header("Content-Type", "image/webp")
	case ".svg":
		c.Header("Content-Type", "image/svg+xml")
		// Sandbox SVG responses so any embedded script cannot run in the app origin.
		c.Header("Content-Security-Policy", "sandbox")
	case ".pdf":
		c.Header("Content-Type", "application/pdf")
	default:
		c.Header("Content-Type", "application/octet-stream")
	}

	// A variant request answered with the original must not be cached long-term,
	// otherwise the generated variant would never be picked up once ready.
	if variantReq {
		c.Header("Cache-Control", "public, max-age=60")
	} else {
		c.Header("Cache-Control", "public, max-age=31536000, immutable")
	}
	if _, err := io.Copy(c.Writer, reader); err != nil {
		c.AbortWithStatus(http.StatusNotFound)
	}
}

func (h *StorageHandler) getObjectReader(ctx context.Context, objectKey string) (io.ReadCloser, error) {
	// Defense in depth: never hand a relative path to the local fallback.
	if strings.Contains(objectKey, "..") {
		return nil, fmt.Errorf("invalid object key %s", objectKey)
	}
	if h.storage != nil {
		if reader, err := h.storage.GetObject(ctx, objectKey); err == nil {
			return reader, nil
		}
	}
	localPath := filepath.Join("storage", "kanban-uploads", objectKey)
	if f, err := os.Open(localPath); err == nil {
		return f, nil
	}
	return nil, fmt.Errorf("object %s not found", objectKey)
}
