"use client";

import { useEffect, useRef, useState, type ReactNode } from "react";
import { getThumbnailUrl } from "@/lib/image-url";

// Retry schedule (ms) for thumbnails whose variant is still being generated by
// the background worker. The worker finishes a 9-photo batch in ~10–15s, so a
// handful of attempts covers it before falling back to the original.
const RETRY_DELAYS_MS = [800, 1600, 3200, 6400, 12800];

// Once a thumbnail has fallen back to the original it periodically re-checks
// whether its variant finished generating, so the grid upgrades to the light
// variant without a reload. The interval and cap keep probing bounded.
const FALLBACK_REPROBE_INTERVAL_MS = 20_000;
const FALLBACK_REPROBE_LIMIT = 9;

// How far from the viewport a card must be before its image starts loading.
const INVIEW_MARGIN_PX = "250px";

// One shared IntersectionObserver gates every ThumbnailImage, so a grid of
// photos registers a single observer instead of one per card.
const pendingLoads = new Map<Element, () => void>();
let sharedObserver: IntersectionObserver | null = null;

function getSharedObserver(): IntersectionObserver {
  if (sharedObserver === null) {
    sharedObserver = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          const onEnter = pendingLoads.get(entry.target);
          if (entry.isIntersecting && onEnter) {
            pendingLoads.delete(entry.target);
            sharedObserver?.unobserve(entry.target);
            onEnter();
          }
        }
      },
      { rootMargin: INVIEW_MARGIN_PX }
    );
  }
  return sharedObserver;
}

interface ThumbnailImageProps {
  src?: string;
  alt?: string;
  /** Main thumbnail width (the `?w=` variant to display). */
  width?: number;
  /** URL to load after retries are exhausted (legacy files without variants). */
  fallbackSrc?: string;
  maxAttempts?: number;
  /**
   * Whether this file is expected to have generated variants. Set to false for
   * items without a `preview_url` (legacy uploads, GIFs, SVGs) so they render
   * the original immediately instead of burning retries on a variant that will
   * never exist.
   */
  expectsVariants?: boolean;
  /** Applied to the container; make it `relative overflow-hidden` to fit. */
  className?: string;
  /** Applied to the image element. */
  imgClassName?: string;
  /** Custom skeleton node shown while the image is not ready yet. */
  skeleton?: ReactNode;
  /** Lazy defers loading until the card approaches the viewport. */
  loading?: "lazy" | "eager";
}

/**
 * ThumbnailImage renders a `?w=` storage variant with a skeleton while it is
 * still being generated by the background worker.
 *
 * Behavior:
 *   - Lazy cards are gated by an IntersectionObserver, so offscreen images
 *     make no network requests until the viewport approaches them.
 *   - While loading, a skeleton is shown until the variant resolves.
 *   - On a "not ready" 404 it retries with exponential backoff.
 *   - After `maxAttempts` it falls back to the original URL (legacy files that
 *     will never get variants). The fallback stays lazy so cards never
 *     download the heavy original unless they are actually on screen, and it
 *     keeps re-probing the variant so the card upgrades once it is ready.
 *   - With `expectsVariants={false}` (GIFs, SVGs, legacy uploads) it renders
 *     the original directly, skipping the retry loop and the skeleton entirely.
 */
export function ThumbnailImage({
  src,
  alt = "",
  width = 400,
  fallbackSrc,
  maxAttempts = RETRY_DELAYS_MS.length,
  expectsVariants = true,
  className,
  imgClassName,
  skeleton,
  loading = "lazy",
}: ThumbnailImageProps) {
  const [inView, setInView] = useState(loading === "eager");
  const [attempt, setAttempt] = useState(0);
  const [loaded, setLoaded] = useState(false);
  const [useFallback, setUseFallback] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);
  const retryTimerRef = useRef<number | null>(null);

  // Reset when the source changes and cancel any pending retry.
  useEffect(() => {
    if (retryTimerRef.current !== null) {
      window.clearTimeout(retryTimerRef.current);
      retryTimerRef.current = null;
    }
    setAttempt(0);
    setLoaded(false);
    setUseFallback(false);
  }, [src, width]);

  // Gate loading until the card approaches the viewport. Cards that are never
  // scrolled near make no requests at all.
  useEffect(() => {
    if (loading === "eager") {
      setInView(true);
      return;
    }
    const el = containerRef.current;
    if (!el) return;
    const observer = getSharedObserver();
    const onEnter = () => setInView(true);
    pendingLoads.set(el, onEnter);
    observer.observe(el);
    return () => {
      if (pendingLoads.get(el) === onEnter) {
        pendingLoads.delete(el);
        observer.unobserve(el);
      }
    };
  }, [loading, src]);

  // While a fallback is engaged the variant may finish generating in the
  // background; probe for it so the card upgrades to the light variant
  // without a reload. The probe uses a detached Image so the visible fallback
  // never flashes back to a skeleton.
  useEffect(() => {
    if (!expectsVariants || !useFallback || !src) return;
    let cancelled = false;
    let remaining = FALLBACK_REPROBE_LIMIT;
    let timer: number | null = null;

    const probeVariant = () => {
      const probe = new Image();
      const settle = (ready: boolean) => {
        if (cancelled) return;
        if (ready) {
          setUseFallback(false);
          setAttempt(0);
          setLoaded(false);
          return;
        }
        remaining -= 1;
        if (remaining > 0) {
          timer = window.setTimeout(probeVariant, FALLBACK_REPROBE_INTERVAL_MS);
        }
      };
      probe.onload = () => settle(true);
      probe.onerror = () => settle(false);
      probe.src = getThumbnailUrl(src, width);
    };

    timer = window.setTimeout(probeVariant, FALLBACK_REPROBE_INTERVAL_MS);
    return () => {
      cancelled = true;
      if (timer !== null) window.clearTimeout(timer);
    };
  }, [expectsVariants, useFallback, src, width]);

  // Clear any pending retry on unmount.
  useEffect(() => {
    return () => {
      if (retryTimerRef.current !== null) window.clearTimeout(retryTimerRef.current);
    };
  }, []);

  if (!src) return null;

  // Without generated variants the original is rendered directly: no retry
  // loop, no skeleton, keep the caller's loading behavior.
  const expectsVariant = expectsVariants !== false;
  const mainSrc = expectsVariant
    ? useFallback
      ? fallbackSrc || src
      : getThumbnailUrl(src, width)
    : fallbackSrc || src;
  const showSkeleton = expectsVariant && !loaded;

  // Variant attempts are eager once the card is on screen so the retry loop
  // always progresses: a lazy <img> that gets remounted out of view never
  // loads, never errors, and stalls the retry chain on a permanent skeleton.
  // Only the legacy fallback (which streams the full-size original) stays lazy.
  const effectiveLoading = useFallback || !expectsVariant ? loading : "eager";

  const handleMainError = () => {
    if (!expectsVariant || useFallback) {
      // The original also failed; stop retrying and reveal the (broken) result.
      setLoaded(true);
      return;
    }
    if (retryTimerRef.current !== null) return; // a retry is already scheduled
    if (attempt + 1 >= maxAttempts) {
      setUseFallback(true);
      return;
    }
    const delay = RETRY_DELAYS_MS[Math.min(attempt, RETRY_DELAYS_MS.length - 1)];
    retryTimerRef.current = window.setTimeout(() => {
      retryTimerRef.current = null;
      setAttempt((a) => a + 1);
    }, delay);
  };

  return (
    <div ref={containerRef} className={className}>
      {inView && showSkeleton &&
        (skeleton ?? <div className="absolute inset-0 animate-pulse bg-surface-l2" />)}

      {inView && (
        <img
          key={`${attempt}:${useFallback ? "fb" : "main"}`}
          src={mainSrc}
          alt={alt}
          loading={effectiveLoading}
          decoding="async"
          onLoad={() => setLoaded(true)}
          onError={handleMainError}
          className={`${imgClassName} transition-opacity duration-300 ${
            loaded ? "opacity-100" : "opacity-0"
          }`}
        />
      )}
    </div>
  );
}
