"use client";

import { useEffect, useRef, useState, type ReactNode } from "react";
import { getThumbnailUrl } from "@/lib/image-url";

// Retry schedule (ms) for thumbnails whose variant is still being generated by
// the background worker. The worker finishes a 9-photo batch in ~10–15s, so a
// handful of attempts covers it before falling back to the original.
const RETRY_DELAYS_MS = [800, 1600, 3200, 6400, 12800];

interface ThumbnailImageProps {
  src?: string;
  alt?: string;
  /** Main thumbnail width (the `?w=` variant to display). */
  width?: number;
  /** URL to load after retries are exhausted (legacy files without variants). */
  fallbackSrc?: string;
  maxAttempts?: number;
  /**
   * Whether this file is expected to have generated variants. Set to false for
   * items without a `preview_url` (legacy uploads, GIFs, SVGs) so they render
   * the original immediately instead of burning retries on a variant that will
   * never exist.
   */
  expectsVariants?: boolean;
  /** Applied to the container; make it `relative overflow-hidden` to fit. */
  className?: string;
  /** Applied to the image element. */
  imgClassName?: string;
  /** Custom skeleton node shown while the image is not ready yet. */
  skeleton?: ReactNode;
  loading?: "lazy" | "eager";
}

/**
 * ThumbnailImage renders a `?w=` storage variant with a skeleton while it is
 * still being generated by the background worker.
 *
 * Behavior:
 *   - Shows a skeleton until the variant resolves.
 *   - On a "not ready" 404 it retries with exponential backoff.
 *   - After `maxAttempts` it falls back to the original URL (legacy files that
 *     will never get variants). The fallback stays lazy so offscreen cards
 *     never download the heavy original.
 *   - With `expectsVariants={false}` (GIFs, SVGs, legacy uploads) it renders
 *     the original directly, skipping the retry loop and the skeleton entirely.
 */
export function ThumbnailImage({
  src,
  alt = "",
  width = 400,
  fallbackSrc,
  maxAttempts = RETRY_DELAYS_MS.length,
  expectsVariants = true,
  className,
  imgClassName,
  skeleton,
  loading = "lazy",
}: ThumbnailImageProps) {
  const [attempt, setAttempt] = useState(0);
  const [loaded, setLoaded] = useState(false);
  const [useFallback, setUseFallback] = useState(false);
  const timerRef = useRef<number | null>(null);

  // Reset when the source changes and cancel any pending retry.
  useEffect(() => {
    if (timerRef.current !== null) {
      window.clearTimeout(timerRef.current);
      timerRef.current = null;
    }
    setAttempt(0);
    setLoaded(false);
    setUseFallback(false);
  }, [src, width]);

  useEffect(() => {
    return () => {
      if (timerRef.current !== null) window.clearTimeout(timerRef.current);
    };
  }, []);

  if (!src) return null;

  // Without generated variants the original is rendered directly: no retry
  // loop, no skeleton, keep the caller's loading behavior.
  const expectsVariant = expectsVariants !== false;
  const mainSrc = expectsVariant
    ? useFallback
      ? fallbackSrc || src
      : getThumbnailUrl(src, width)
    : fallbackSrc || src;
  const showSkeleton = expectsVariant && !loaded;

  // Variant attempts are eager so the retry loop always progresses, even for
  // cards offscreen: a lazy <img> that gets remounted out of view never loads,
  // never errors, and stalls the retry chain on a permanent skeleton. Only the
  // legacy fallback (which streams the full-size original) stays lazy, so
  // offscreen cards never download the heavy original.
  const effectiveLoading = useFallback || !expectsVariant ? loading : "eager";

  const handleMainError = () => {
    if (!expectsVariant || useFallback) {
      // The original also failed; stop retrying and reveal the (broken) result.
      setLoaded(true);
      return;
    }
    if (timerRef.current !== null) return; // a retry is already scheduled
    if (attempt + 1 >= maxAttempts) {
      setUseFallback(true);
      return;
    }
    const delay = RETRY_DELAYS_MS[Math.min(attempt, RETRY_DELAYS_MS.length - 1)];
    timerRef.current = window.setTimeout(() => {
      timerRef.current = null;
      setAttempt((a) => a + 1);
    }, delay);
  };

  return (
    <div className={className}>
      {showSkeleton &&
        (skeleton ?? <div className="absolute inset-0 animate-pulse bg-surface-l2" />)}

      <img
        key={`${attempt}:${useFallback ? "fb" : "main"}`}
        src={mainSrc}
        alt={alt}
        loading={effectiveLoading}
        decoding="async"
        onLoad={() => setLoaded(true)}
        onError={handleMainError}
        className={`${imgClassName} transition-opacity duration-300 ${
          loaded ? "opacity-100" : "opacity-0"
        }`}
      />
    </div>
  );
}
